class ShapedTemplate:
    @staticmethod
    def _hasAttributes(attributes, names):
        names = names if type(names) == list else [names]
        for name in names:
            if attributes.get(name, "") != "":
                return True
        return False

    @classmethod
    def template_5e_shaped_wip(klass, attributes):
        title = attributes.get("title", "")
        classes = []
        if klass._hasAttributes(attributes, "continuous_header"):
            classes.append("continuous-header")
        if klass._hasAttributes(attributes, "continuous"):
            classes.append("continuous")
        if klass._hasAttributes(attributes, "continuous_footer"):
            classes.append("continuous-footer")
        advantage_type = 0
        if klass._hasAttributes(attributes, ["2d20kh1", "3d10kh2", "4d6kh3"]):
            advantage_type = 1
        elif klass._hasAttributes(attributes, ["3d20kh1", "4d10kh2", "5d6kh3"]):
            advantage_type = 2
        elif klass._hasAttributes(attributes, ["2d20kl1", "3d10kl2", "4d6kl3"]):
            advantage_type = -1
        elif klass._hasAttributes(attributes, ["3d20kl1", "4d10kl2", "5d6kl3"]):
            advantage_type = -2
        advantage_disadvantage = ""
        if advantage_type != 0:
            plus = "+" if advantage_type == 2 or advantage_type == -2 else ""
            advantage_disadvantage = """
                <div class="sheet-tooltip">
                    <div class="tooltip-toggle-text advantage-circle {}advantage">{}</div>
                    <div class="sheet-tooltip-content-left sheet-tooltip-small sheet-small-label"><span>{}</span>{}</div>
                </div>""".format("dis" if advantage_type < 0 else "", plus, "Disadvantage" if advantage_type < 0 else "Advantage", plus)
        # TODO: nope!
        if title != "":
            title = """
            <div class="rt-title-wrap"><span class="rt-title"><span class="rt-title-name">{}</span><span class="inline-block"><span class="shaped-row uses-recharge-cost-wrap{}">{{#uses}}<span>&nbsp;(</span>{{/uses}} {{#uses_max}} {{^uses}}<span>(</span>{{/uses}} {{/uses_max}} {{#recharge}} {{^uses}} {{^uses_max}}<span>&nbsp;(</span>{{/uses_max}} {{/uses}} {{/recharge}} {{#cost}} {{^uses}} {{^uses_max}} {{^recharge}}<span>&nbsp;(</span>{{/recharge}} {{/uses_max}} {{/uses}} {{/cost}} {{#uses}}<span>{{uses}}</span>{{/uses}} {{#uses_max}}<span>/{{uses_max}}</span>{{/uses_max}} {{#recharge}} {{#uses_max}},&nbsp;{{/uses_max}}<span data-i18n="{{recharge}}"></span>{{/recharge}} {{#cost}} {{#uses_max}},&nbsp;{{/uses_max}} {{#recharge}}{{^uses_max}},&nbsp;{{/uses_max}}{{/recharge}}<span data-i18n="{{cost}}"></span>{{/cost}} {{#uses}}<span>)</span>{{/uses}} {{#uses_max}} {{^uses}}<span>)</span>{{/uses}} {{/uses_max}} {{#recharge}} {{^uses}} {{^uses_max}}<span>)</span>{{/uses_max}} {{/uses}} {{/recharge}} {{#cost}} {{^uses}} {{^uses_max}} {{^recharge}}<span>)</span>{{/recharge}} {{/uses_max}} {{/uses}} {{/cost}}</span>
                </span>
                </span>
            </div>""".format(title, " gm-info-block" if klass._hasAttributes(attributes, "hide_recharge") else "", )
        return """
    <div class="rt-card boring-box-wrapper {}">
        <div class="grid-box boring-box">
            <div class="boring-box-top-left"></div>
            <div class="boring-box-expand-top"></div>
            <div class="boring-box-top-right"></div>
            <div class="boring-box-expand-left"></div>
            <div class="box-middle"></div>
            <div class="boring-box-expand-right"></div>
            <div class="boring-box-bottom-left"></div>
            <div class="boring-box-expand-bottom"></div>
            <div class="boring-box-bottom-right"></div>
        </div>
        <div class="box-inner">
            <div class="sheet-tooltip-position-wrapper">{}
            </div>{}
            <div class="rt-subheader">{{#spell_first_line}}
                <div class="italic">{{spell_level}}{{#cast_as_level}}&nbsp;(<span class="lowercase" data-i18n="AS">as</span>&nbsp;{{cast_as_level}}){{/cast_as_level}}{{#school}}&nbsp;<span class="lowercase">{{school}}</span>{{/school}}{{#ritual}} (<span class="lowercase" data-i18n="RITUAL">ritual</span>){{/ritual}}</div>{{/spell_first_line}} {{#statblock_first_line}}
                <div class="italic">{{#size}}{{size}}{{/size}}{{#type}} {{type}}{{/type}}{{#race}} {{race}}{{/race}}{{#alignment}}, {{alignment}}{{/alignment}}</div>{{/statblock_first_line}} {{#show_character_name}}
                <div class="rt-character-name">{{character_name}}</div>{{/show_character_name}} {{#subheader}}
                <div>{{subheader}}</div>{{/subheader}}</div>{{#emote}}
            <p class="rt-emote">{{character_name}}&nbsp;{{emote}}</p>{{/emote}}
            <div class="rt-content">{{#criteria}} {{criteria}} {{/criteria}} {{#entities}}
                <div class="entity-scroller">{{entities}}</div>{{/entities}} {{#spell}} {{#casting_time}}
                <div class="no-border"><span class="bold"><span data-i18n="CASTING_TIME">Casting Time</span>:</span><span>&nbsp;</span><span>{{casting_time}}</span></div>{{/casting_time}} {{#range}}
                <div class="no-border"><span class="bold"><span data-i18n="RANGE">Range</span>:</span><span>&nbsp;</span><span>{{range}}</span></div>{{/range}} {{#reach}}
                <div class="no-border"><span class="bold"><span data-i18n="REACH">Reach</span>:</span><span>&nbsp;</span><span>{{reach}}</span></div>{{/reach}} {{#components}}
                <div class="no-border"><span class="bold"><span data-i18n="COMPONENTS">Components</span>:</span><span>&nbsp;</span><span>{{components}} {{#materials}}&nbsp;({{materials}}){{/materials}}</span></div>{{/components}} {{#duration}}
                <div class="no-border"><span class="bold"><span data-i18n="DURATION">Duration</span>:</span><span>&nbsp;</span><span>{{duration}}</span></div>{{/duration}} {{#content}}
                <div class="{{#hide_content}}gm-info-block{{/hide_content}}">{{content}}</div>{{/content}} {{#higher_level}}
                <div class="{{#hide_content}}gm-info-block{{/hide_content}}">{{higher_level}}</div>{{/higher_level}} {{/spell}} {{#text_top}}
                <div class="output">{{text_top}}</div>{{/text_top}} {{#roll1}}
                <div class="shaped-row align-flex-end{{#ability}}{{#hide_ability_checks}} gm-info-flex{{/hide_ability_checks}}{{/ability}}{{#saving_throw}}{{#hide_saving_throws}} gm-info-flex{{/hide_saving_throws}}{{/saving_throw}}"><span class="output{{#roll2}} pad-r-md{{/roll2}}">{{roll1}}</span>{{#roll2}}<span class="output pad-l-md border-left">{{roll2}}</span>{{/roll2}}</div>{{/roll1}} {{#attack1}}
                <div class="{{#hide_attack}}gm-info-block{{/hide_attack}}">{{#attack_type}}
                    <div class="italic"><span data-i18n="{{attack_type}}"></span>:</div>{{/attack_type}} {{^attack_type}} {{#attack_type_macro}}
                    <div class="italic"><span>{{attack_type_macro}}</span></div>{{/attack_type_macro}} {{/attack_type}}
                    <div class="shaped-row align-flex-end"><span class="output{{#attack2}} pad-r-md{{/attack2}}">{{attack1}}</span>{{#attack2}}<span class="output pad-l-md border-left">{{attack2}}</span>{{/attack2}}<span>&nbsp;</span><span data-i18n="TO_HIT"></span>{{#targetName}}<span>&nbsp;</span><span>{{targetName}}</span>{{/targetName}} {{#targetAC}}<span>&nbsp;</span><span data-i18n="AC">AC</span><span>&nbsp;</span><span class="{{#hide_target_ac}}gm-info-inline-block{{/hide_target_ac}}">{{targetAC}}</span>{{/targetAC}} {{#reach}}<span>,&nbsp;</span>{{/reach}} {{#range}} {{^reach}}<span>,&nbsp;</span>{{/reach}} {{/range}} {{#reach}}<span data-i18n="REACH" class="lowercase"></span><span>&nbsp;</span><span>{{reach}}</span>{{/reach}} {{#range}} {{#reach}}<span>&nbsp;</span><span data-i18n="OR"></span><span>&nbsp;</span>{{/reach}}<span data-i18n="RANGE" class="lowercase"></span><span>&nbsp;</span><span>{{range}}</span>{{#ammo}}<span>,&nbsp;</span><span><span class="ammo-wrapper">{{ammo}}</span>{{#ammo_name}} {{ammo_name}} {{/ammo_name}} {{^ammo_name}}<span class="lowercase" data-i18n="AMMO">ammo</span>{{/ammo_name}}</span>{{/ammo}} {{/range}}</div>
                </div>{{/attack1}} {{#has_attack_damage}}
                <div class="zebra{{#hide_damage}} gm-info-block{{/hide_damage}}">{{#attack_damage_macro}}
                    <div class="italic">{{#rollWasCrit() attack1}} {{attack_damage_crit_macro}} {{/rollWasCrit() attack1}} {{#^rollWasCrit() attack1}} {{#rollWasCrit() attack2}} {{attack_damage_crit_macro}} {{/rollWasCrit() attack2}} {{#^rollWasCrit() attack2}} {{attack_damage_macro}} {{/^rollWasCrit() attack2}} {{^attack2}} {{attack_damage_macro}} {{/attack2}} {{/^rollWasCrit() attack1}}</div>{{/attack_damage_macro}} {{#attack_damage}}
                    <div class="shaped-row align-flex-end"><span class="output">{{attack_damage}}</span>{{#rollWasCrit() attack1}}<span class="output">+{{attack_damage_crit}}</span>{{/rollWasCrit() attack1}} {{#^rollWasCrit() attack1}} {{#rollWasCrit() attack2}}<span class="output">+{{attack_damage_crit}}</span>{{/rollWasCrit() attack2}} {{/^rollWasCrit() attack1}} {{#force_crit}}<span class="output">+{{attack_damage_crit}}</span>{{/force_crit}}<span>&nbsp;</span>{{#attack_damage_type}}<span>{{attack_damage_type}}</span><span>&nbsp;</span>{{/attack_damage_type}}<span class="lowercase" data-i18n="DAMAGE">damage</span>{{#attack_second_damage}}<span>&nbsp;</span><span data-i18n="PLUS" class="lowercase"></span>{{/attack_second_damage}}</div>{{#attack_second_damage}}
                    <div class="shaped-row align-flex-end"><span class="output">{{attack_second_damage}}</span>{{#rollWasCrit() attack1}}<span class="output">+{{attack_second_damage_crit}}</span>{{/rollWasCrit() attack1}} {{#^rollWasCrit() attack1}} {{#rollWasCrit() attack2}}<span class="output">+{{attack_second_damage_crit}}</span>{{/rollWasCrit() attack2}} {{/^rollWasCrit() attack1}} {{#force_crit}}<span class="output">+{{attack_second_damage_crit}}</span>{{/force_crit}}<span>&nbsp;</span>{{#attack_second_damage_type}}<span>{{attack_second_damage_type}}</span><span>&nbsp;</span>{{/attack_second_damage_type}}<span class="lowercase" data-i18n="DAMAGE">damage</span></div>{{/attack_second_damage}} {{/attack_damage}}</div>{{/has_attack_damage}} {{#saving_throw_dc}}
                <div>{{#saving_throw_dc}} {{#targetName}}
                    <div class="output-label"><span data-i18n="VS"></span><span>{{targetName}}</span></div>{{/targetName}}
                    <div><span class="output"><span class="{{#hide_saving_throw_dc}}gm-info-inline-block{{/hide_saving_throw_dc}}"><span data-i18n="DC"></span><span>&nbsp;</span>{{saving_throw_dc}}</span>{{#saving_throw_vs_ability}}<span>&nbsp;</span><span>[<span data-i18n="{{saving_throw_vs_ability}}">{{saving_throw_vs_ability}}</span>](~selected|shaped_{{saving_throw_vs_ability}}_saving_throw)</span>{{/saving_throw_vs_ability}}<span>&nbsp;</span><span data-i18n="SAVING_THROW" class="lowercase"></span></span>
                    </div>{{/saving_throw_dc}} {{#saving_throw_success}}
                    <div class="{{#hide_saving_throw_success}}gm-info-block{{/hide_saving_throw_success}}">
                        <div class="italic"><span data-i18n="SAVING_THROW_SUCCESS"></span>:</div>
                        <div>{{saving_throw_success}}</div>
                    </div>{{/saving_throw_success}}</div>{{/saving_throw_dc}} {{#has_saving_throw_damage}}
                <div class="zebra{{#hide_damage}} gm-info-block{{/hide_damage}}">{{#saving_throw_damage_macro}}
                    <div class="italic">{{saving_throw_damage_macro}}</div>{{/saving_throw_damage_macro}} {{#saving_throw_damage}}
                    <div class="shaped-row align-flex-end"><span>{{saving_throw_damage}}</span>{{#saving_throw_damage_type}}<span>&nbsp;</span><span>{{saving_throw_damage_type}}</span><span>&nbsp;</span>{{/saving_throw_damage_type}}<span class="lowercase" data-i18n="DAMAGE">damage</span>{{#saving_throw_second_damage}}<span>&nbsp;</span><span data-i18n="PLUS" class="lowercase"></span>{{/saving_throw_second_damage}}</div>{{#saving_throw_second_damage}}
                    <div class="shaped-row align-flex-end"><span>{{saving_throw_second_damage}}</span><span>&nbsp;</span>{{#saving_throw_second_damage_type}}<span>{{saving_throw_second_damage_type}}</span><span>&nbsp;</span>{{/saving_throw_second_damage_type}}<span class="lowercase" data-i18n="DAMAGE">damage</span></div>{{/saving_throw_second_damage}} {{/saving_throw_damage}}</div>{{/has_saving_throw_damage}} {{#other_damage}}
                <div class="zebra{{#hide_damage}} gm-info-flex{{/hide_damage}}">
                    <div class="shaped-row align-flex-end"><span class="output">{{other_damage}}</span>{{#rollWasCrit() attack1}}<span class="output">+{{other_damage_crit}}</span>{{/rollWasCrit() attack1}} {{#^rollWasCrit() attack1}} {{#rollWasCrit() attack2}}<span class="output">+{{other_damage_crit}}</span>{{/rollWasCrit() attack2}} {{/^rollWasCrit() attack1}}<span>&nbsp;</span>{{#other_damage_type}}<span>{{other_damage_type}}</span><span>&nbsp;</span>{{/other_damage_type}}<span class="lowercase" data-i18n="DAMAGE">damage</span>{{#other_second_damage}}<span>&nbsp;</span><span data-i18n="PLUS" class="lowercase"></span>{{/other_second_damage}}</div>{{#other_second_damage}}
                    <div class="shaped-row align-flex-end"><span class="output">{{other_second_damage}}</span>{{#rollWasCrit() attack1}}<span class="output">+{{other_second_damage_crit}}</span>{{/rollWasCrit() attack1}} {{#^rollWasCrit() attack1}} {{#rollWasCrit() attack2}}<span class="output">+{{other_second_damage_crit}}</span>{{/rollWasCrit() attack2}} {{/^rollWasCrit() attack1}}<span>&nbsp;</span>{{#other_second_damage_type}}<span>{{other_second_damage_type}}</span><span>&nbsp;</span>{{/other_second_damage_type}}<span class="lowercase" data-i18n="DAMAGE">damage</span></div>{{/other_second_damage}}</div>{{/other_damage}} {{#heal}}
                <div>
                    <div class="italic"><span data-i18n="REGAIN"></span></div>
                    <div>{{heal}}<span>&nbsp;</span><span class="lowercase" data-i18n="HIT_POINTS"></span></div>
                </div>{{/heal}} {{#death_saving_throw_chances}}
                <div>{{#death_saving_throw_successes}}
                    <div><span data-i18n="SUCCESSES">Successes</span>&nbsp;{{death_saving_throw_successes}} / {{death_saving_throw_chances}}</div>{{/death_saving_throw_successes}} {{#death_saving_throw_failures}}
                    <div><span data-i18n="FAILURES">Failures</span>&nbsp;{{death_saving_throw_failures}} / {{death_saving_throw_chances}}</div>{{/death_saving_throw_failures}}</div>{{/death_saving_throw_chances}} {{#spell_list}}
                <div class="output{{#prepared_matters}} prepared-matters{{/prepared_matters}}">{{#has_spell_points}}
                    <div class="rt-title spell-points">{{spell_points}}/{{spell_points_max}}&nbsp;<span class="lowercase">{{spell_points_name}}</span>{{#spell_points_limit}},&nbsp;<span data-i18n="LIMIT" class="lowercase">limit</span>&nbsp;{{spell_points_limit}}{{/spell_points_limit}}</div>{{/has_spell_points}} {{#has_warlock_slots}}
                    <div><span><span data-i18n="WARLOCK"></span>{{#warlock_spell_slots_remaining}}&nbsp;({{warlock_spell_slots_remaining}}){{/warlock_spell_slots_remaining}}:</span><span>&nbsp;</span>{{warlock_spell_slot_level}}</div>{{/has_warlock_slots}} {{#spell_level_0_show}}
                    <div><span><span data-i18n="CANTRIPS">Cantrips</span><span>:</span><span>&nbsp;</span></span><span class="spells-wrapper">{{cantrips}}</span></div>{{/spell_level_0_show}} {{#spell_level_1_show}}
                    <div><span><span data-i18n="1ST_LEVEL"></span>{{^has_spell_slots}}{{^has_spell_points}}:{{/has_spell_points}}{{/has_spell_slots}}{{#has_spell_slots}}{{^spell_level_1_slots_remaining}}:{{/spell_level_1_slots_remaining}}{{/has_spell_slots}} {{#has_spell_slots}} {{#spell_level_1_slots_remaining}} ({{spell_level_1_slots_remaining}}){{^has_spell_points}}:{{/has_spell_points}} {{/spell_level_1_slots_remaining}} {{/has_spell_slots}} {{#has_spell_points}} ({{spell_level_1_cost}}&nbsp;<span class="lowercase">{{spell_points_name}}</span>): {{/has_spell_points}}</span><span class="spells-wrapper">{{spell_level_1_spells}}</span></div>{{/spell_level_1_show}} {{#spell_level_2_show}}
                    <div><span><span data-i18n="2ND_LEVEL"></span>{{^has_spell_slots}}{{^has_spell_points}}:{{/has_spell_points}}{{/has_spell_slots}}{{#has_spell_slots}}{{^spell_level_2_slots_remaining}}:{{/spell_level_2_slots_remaining}}{{/has_spell_slots}} {{#has_spell_slots}} {{#spell_level_2_slots_remaining}} ({{spell_level_2_slots_remaining}}){{^has_spell_points}}:{{/has_spell_points}} {{/spell_level_2_slots_remaining}} {{/has_spell_slots}} {{#has_spell_points}} ({{spell_level_2_cost}}&nbsp;<span class="lowercase">{{spell_points_name}}</span>): {{/has_spell_points}}</span><span class="spells-wrapper">{{spell_level_2_spells}}</span></div>{{/spell_level_2_show}} {{#spell_level_3_show}}
                    <div><span><span data-i18n="3RD_LEVEL"></span>{{^has_spell_slots}}{{^has_spell_points}}:{{/has_spell_points}}{{/has_spell_slots}}{{#has_spell_slots}}{{^spell_level_3_slots_remaining}}:{{/spell_level_3_slots_remaining}}{{/has_spell_slots}} {{#has_spell_slots}} {{#spell_level_3_slots_remaining}} ({{spell_level_3_slots_remaining}}){{^has_spell_points}}:{{/has_spell_points}} {{/spell_level_3_slots_remaining}} {{/has_spell_slots}} {{#has_spell_points}} ({{spell_level_3_cost}}&nbsp;<span class="lowercase">{{spell_points_name}}</span>): {{/has_spell_points}}</span><span class="spells-wrapper">{{spell_level_3_spells}}</span></div>{{/spell_level_3_show}} {{#spell_level_4_show}}
                    <div><span><span data-i18n="4TH_LEVEL"></span>{{^has_spell_slots}}{{^has_spell_points}}:{{/has_spell_points}}{{/has_spell_slots}}{{#has_spell_slots}}{{^spell_level_4_slots_remaining}}:{{/spell_level_4_slots_remaining}}{{/has_spell_slots}} {{#has_spell_slots}} {{#spell_level_4_slots_remaining}} ({{spell_level_4_slots_remaining}}){{^has_spell_points}}:{{/has_spell_points}} {{/spell_level_4_slots_remaining}} {{/has_spell_slots}} {{#has_spell_points}} ({{spell_level_4_cost}}&nbsp;<span class="lowercase">{{spell_points_name}}</span>): {{/has_spell_points}}</span><span class="spells-wrapper">{{spell_level_4_spells}}</span></div>{{/spell_level_4_show}} {{#spell_level_5_show}}
                    <div><span><span data-i18n="5TH_LEVEL"></span>{{^has_spell_slots}}{{^has_spell_points}}:{{/has_spell_points}}{{/has_spell_slots}}{{#has_spell_slots}}{{^spell_level_5_slots_remaining}}:{{/spell_level_5_slots_remaining}}{{/has_spell_slots}} {{#has_spell_slots}} {{#spell_level_5_slots_remaining}} ({{spell_level_5_slots_remaining}}){{^has_spell_points}}:{{/has_spell_points}} {{/spell_level_5_slots_remaining}} {{/has_spell_slots}} {{#has_spell_points}} ({{spell_level_5_cost}}&nbsp;<span class="lowercase">{{spell_points_name}}</span>): {{/has_spell_points}}</span><span class="spells-wrapper">{{spell_level_5_spells}}</span></div>{{/spell_level_5_show}} {{#spell_level_6_show}}
                    <div><span><span data-i18n="6TH_LEVEL"></span>{{^has_spell_slots}}{{^has_spell_points}}:{{/has_spell_points}}{{/has_spell_slots}}{{#has_spell_slots}}{{^spell_level_6_slots_remaining}}:{{/spell_level_6_slots_remaining}}{{/has_spell_slots}} {{#has_spell_slots}} {{#spell_level_6_slots_remaining}} ({{spell_level_6_slots_remaining}}){{^has_spell_points}}:{{/has_spell_points}} {{/spell_level_6_slots_remaining}} {{/has_spell_slots}} {{#has_spell_points}} ({{spell_level_6_cost}}&nbsp;<span class="lowercase">{{spell_points_name}}</span>): {{/has_spell_points}}</span><span class="spells-wrapper">{{spell_level_6_spells}}</span></div>{{/spell_level_6_show}} {{#spell_level_7_show}}
                    <div><span><span data-i18n="7TH_LEVEL"></span>{{^has_spell_slots}}{{^has_spell_points}}:{{/has_spell_points}}{{/has_spell_slots}}{{#has_spell_slots}}{{^spell_level_7_slots_remaining}}:{{/spell_level_7_slots_remaining}}{{/has_spell_slots}} {{#has_spell_slots}} {{#spell_level_7_slots_remaining}} ({{spell_level_7_slots_remaining}}){{^has_spell_points}}:{{/has_spell_points}} {{/spell_level_7_slots_remaining}} {{/has_spell_slots}} {{#has_spell_points}} ({{spell_level_7_cost}}&nbsp;<span class="lowercase">{{spell_points_name}}</span>): {{/has_spell_points}}</span><span class="spells-wrapper">{{spell_level_7_spells}}</span></div>{{/spell_level_7_show}} {{#spell_level_8_show}}
                    <div><span><span data-i18n="8TH_LEVEL"></span>{{^has_spell_slots}}{{^has_spell_points}}:{{/has_spell_points}}{{/has_spell_slots}}{{#has_spell_slots}}{{^spell_level_8_slots_remaining}}:{{/spell_level_8_slots_remaining}}{{/has_spell_slots}} {{#has_spell_slots}} {{#spell_level_8_slots_remaining}} ({{spell_level_8_slots_remaining}}){{^has_spell_points}}:{{/has_spell_points}} {{/spell_level_8_slots_remaining}} {{/has_spell_slots}} {{#has_spell_points}} ({{spell_level_8_cost}}&nbsp;<span class="lowercase">{{spell_points_name}}</span>): {{/has_spell_points}}</span><span class="spells-wrapper">{{spell_level_8_spells}}</span></div>{{/spell_level_8_show}} {{#spell_level_9_show}}
                    <div><span><span data-i18n="9TH_LEVEL"></span>{{^has_spell_slots}}{{^has_spell_points}}:{{/has_spell_points}}{{/has_spell_slots}}{{#has_spell_slots}}{{^spell_level_9_slots_remaining}}:{{/spell_level_9_slots_remaining}}{{/has_spell_slots}} {{#has_spell_slots}} {{#spell_level_9_slots_remaining}} ({{spell_level_9_slots_remaining}}){{^has_spell_points}}:{{/has_spell_points}} {{/spell_level_9_slots_remaining}} {{/has_spell_slots}} {{#has_spell_points}} ({{spell_level_9_cost}}&nbsp;<span class="lowercase">{{spell_points_name}}</span>): {{/has_spell_points}}</span><span class="spells-wrapper">{{spell_level_9_spells}}</span></div>{{/spell_level_9_show}}</div>{{/spell_list}} {{^spell}} {{#content}}
                <div class="no-border{{#hide_content}} gm-info-block{{/hide_content}}">{{content}}</div>{{/content}} {{/spell}} {{#hp_max}}
                <div class="shaped-row output"><span>{{hp}}{{#hp}}{{/hp}}</span><span>/</span><span>{{hp_max}}</span></div>
                <div class="shaped-row">{{#temp_hp}}<span>{{temp_hp}}</span><span>&nbsp;</span><span data-i18n="HIT_POINTS_TEMP" class="lowercase"></span>{{/temp_hp}} {{#hp_max_reduced}} {{#temp_hp}}<span>,&nbsp;</span>{{/temp_hp}}<span data-i18n="HIT_POINT_MAXIMUM_REDUCED_BY" class="lowercase"></span><span>&nbsp;</span><span>{{hp_max_reduced}}</span>{{/hp_max_reduced}}</div>{{/hp_max}} {{#text_center}}
                <div class="center">{{text_center}}</div>{{/text_center}} {{#text}}
                <div>{{text}}</div>{{/text}} {{#text_big}}
                <div class="output">{{text_big}}</div>{{/text_big}} {{#macros}}
                <div>{{macros}}</div>{{/macros}} {{#allprops() freetext text text_center text_big macros text_top character_name saving_throw title ignore d20 1d20 show_character_name subheader cost per_use uses uses_max roll1 roll2 2d20kh1 2d20kl1 3d20kh1 3d20kl1 2d10 3d10kh2 3d10kl2 4d10kh2 4d10kl2 3d6 4d6kh3 4d6kl3 5d6kh3 5d6kl3 ability emote death_saving_throw death_saving_throw_chances death_saving_throw_successes death_saving_throw_failures targetAC targetName crit_name crit_text attack1 attack2 attack_type attack_type_macro has_attack_damage attack_damage_macro attack_damage_crit_macro force_crit attack_damage attack_damage_type attack_damage_crit attack_second_damage attack_second_damage_type attack_second_damage_crit has_saving_throw_damage saving_throw_damage_macro saving_throw_damage saving_throw_damage_type saving_throw_damage_crit saving_throw_second_damage saving_throw_second_damage_type other_damage other_damage_type other_damage_crit other_second_damage other_second_damage_type other_second_damage_crit ranged reach range ammo ammo_name spell spell_first_line spell_repeat spell_list prepared_matters saving_throw_dc saving_throw_vs_ability saving_throw_success spell_level school ritual content higher_level cast_as_level heal casting_time duration components materials hide_ability_checks hide_saving_throws hide_target_ac hide_saving_throw_dc hide_content hide_freetext hide_attack hide_damage hide_saving_throw_success recharge hide_recharge fx armor equipment cantrips spell_level_0_spells spell_level_0_cost spell_level_0_slots_remaining spell_level_0_show spell_level_1_spells spell_level_1_cost spell_level_1_slots_remaining spell_level_1_show spell_level_2_spells spell_level_2_cost spell_level_2_slots_remaining spell_level_2_show spell_level_3_spells spell_level_3_cost spell_level_3_slots_remaining spell_level_3_show spell_level_4_spells spell_level_4_cost spell_level_4_slots_remaining spell_level_4_show spell_level_5_spells spell_level_5_cost spell_level_5_slots_remaining spell_level_5_show spell_level_6_spells spell_level_6_cost spell_level_6_slots_remaining spell_level_6_show spell_level_7_spells spell_level_7_cost spell_level_7_slots_remaining spell_level_7_show spell_level_8_spells spell_level_8_cost spell_level_8_slots_remaining spell_level_8_show spell_level_9_spells spell_level_9_cost spell_level_9_slots_remaining spell_level_9_show has_spell_slots has_spell_points spell_points spell_points_max spell_points_limit spell_points_name has_warlock_slots warlock_spell_slots_remaining warlock_spell_slot_level hp hp_max temp_hp hp_max_reduced repeating_item offense utility action reaction legendaryaction lairaction regionaleffect racialtrait classfeature feat trait continuous continuous_header continuous_footer entities criteria statblock_first_line size type race alignment}}
                <div><span class="bold italic">{{key}}.</span><span>&nbsp;</span>{{value}}</div>{{/allprops() freetext text text_center text_big macros text_top character_name saving_throw title ignore d20 1d20 show_character_name subheader cost per_use uses uses_max roll1 roll2 2d20kh1 2d20kl1 3d20kh1 3d20kl1 2d10 3d10kh2 3d10kl2 4d10kh2 4d10kl2 3d6 4d6kh3 4d6kl3 5d6kh3 5d6kl3 ability emote death_saving_throw death_saving_throw_chances death_saving_throw_successes death_saving_throw_failures targetAC targetName crit_name crit_text attack1 attack2 attack_type attack_type_macro has_attack_damage attack_damage_macro attack_damage_crit_macro force_crit attack_damage attack_damage_type attack_damage_crit attack_second_damage attack_second_damage_type attack_second_damage_crit has_saving_throw_damage saving_throw_damage_macro saving_throw_damage saving_throw_damage_type saving_throw_damage_crit saving_throw_second_damage saving_throw_second_damage_type other_damage other_damage_type other_damage_crit other_second_damage other_second_damage_type other_second_damage_crit ranged reach range ammo ammo_name spell spell_first_line spell_repeat spell_list prepared_matters saving_throw_dc saving_throw_vs_ability saving_throw_success spell_level school ritual content higher_level cast_as_level heal casting_time duration components materials hide_ability_checks hide_saving_throws hide_target_ac hide_saving_throw_dc hide_content hide_freetext hide_attack hide_damage hide_saving_throw_success recharge hide_recharge fx armor equipment cantrips spell_level_0_spells spell_level_0_cost spell_level_0_slots_remaining spell_level_0_show spell_level_1_spells spell_level_1_cost spell_level_1_slots_remaining spell_level_1_show spell_level_2_spells spell_level_2_cost spell_level_2_slots_remaining spell_level_2_show spell_level_3_spells spell_level_3_cost spell_level_3_slots_remaining spell_level_3_show spell_level_4_spells spell_level_4_cost spell_level_4_slots_remaining spell_level_4_show spell_level_5_spells spell_level_5_cost spell_level_5_slots_remaining spell_level_5_show spell_level_6_spells spell_level_6_cost spell_level_6_slots_remaining spell_level_6_show spell_level_7_spells spell_level_7_cost spell_level_7_slots_remaining spell_level_7_show spell_level_8_spells spell_level_8_cost spell_level_8_slots_remaining spell_level_8_show spell_level_9_spells spell_level_9_cost spell_level_9_slots_remaining spell_level_9_show has_spell_slots has_spell_points spell_points spell_points_max spell_points_limit spell_points_name has_warlock_slots warlock_spell_slots_remaining warlock_spell_slot_level hp hp_max temp_hp hp_max_reduced repeating_item offense utility action reaction legendaryaction lairaction regionaleffect racialtrait classfeature feat trait continuous continuous_header continuous_footer entities criteria statblock_first_line size type race alignment}} {{#freetext}}
                <div class="{{#hide_freetext}} gm-info-block{{/hide_freetext}}">{{freetext}}</div>{{/freetext}} {{#crit_name}} {{#rollWasCrit() attack1}}
                <div><span class="bold italic">{{crit_name}}.</span><span>&nbsp;</span>{{crit_text}}</div>{{/rollWasCrit() attack1}} {{#^rollWasCrit() attack1}} {{#rollWasCrit() attack2}}
                <div><span class="bold italic">{{crit_name}}.</span><span>&nbsp;</span>{{crit_text}}</div>{{/rollWasCrit() attack2}} {{/^rollWasCrit() attack1}} {{/crit_name}}</div>
        </div>
    </div>""".format(" ".join(classes), advantage_disadvantage, title)